spring:
  application:
    name: linapi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  session:
    timeout: 86400
    store-type: redis
  # redis ??
#  redis:
#    port: 6379
#    host: localhost
#    database: 0
server:
  port: 7529
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
#      logic-delete-value: 1 # ??????(??? 1)
#      logic-not-delete-value: 0 # ??????(??? 0)
springdoc:
  api-docs:
    enabled: true
    # 访问路径：http://localhost:7529/v3/api-docs
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    # 访问路径：http://localhost:7529/swagger-ui/index.html#/
    path: /index.html
api:
  client:
    access-key: lin
    secret-key: abcdefg
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    logger: slf4j
  protocol:
    name: tri
    port: 50052
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848